---
# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/sds/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/sds/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/sds/overcommit#configuration
#
# Uncomment the following lines to make the configuration take effect.

PreCommit:
  # Extend default config at
  # https://github.com/sds/overcommit/blob/master/config/default.yml
  ALL:
    exclude:
      # Files are templated and the raw version is not always valid
      # syntax as a result; these will be tested in pytest after being
      # templated.
      - '{{cookiecutter.project_slug}}/**/*'
  BrokenSymlinks:
    enabled: true
    description: 'Check for broken symlinks'
    quiet: true
    exclude:
      # This is a symlink to sibling checkout of plate-spinner, used
      # only in local development
      - config/env.1p
  PythonFlake8:
    enabled: true
    on_warn: fail
  ShellCheck:
    enabled: true
    on_warn: fail
    include:
      - '.envrc'
      - '**/*.sh'
  YamlLint:
    enabled: true
    flags: ['-c', '.yamllint.yml', '--format=parsable', '--strict']
    on_warn: fail
  CircleCi:
    required_executable: 'circleci'
    flags: ['config', 'validate']
    include:
      - '.circleci/config.yml'
    enabled: true
  Punchlist:
    command: ['bundle', 'exec', 'punchlist']
    enabled: true
    problem_on_unmodified_line: warn

#PostCheckout:
#  ALL: # Special hook name that customizes all hooks of this type
#    quiet: true # Change all post-checkout hooks to only display output on failure
#
#  IndexTags:
#    enabled: true # Generate a tags file with `ctags` each time HEAD changes

# The tests in cookiecutter-multicli take a bit too long to repeat
# between a push and CircleCI.
#
# PrePush:
# takes too long; might as well just run it once in CI
#  Pytest:
#    enabled: true
